### ISSUE TITLE
Elasticsearch as Performance Data Backend

### ISSUE THREAD

**Issue by duylong** [statusengine/worker#1]
Hi,

I use already Elasticsearch with Grafana. Elasticsearch can also accept time series. 
It would be interesting to add Elasticsearch as backend.

**Comment by duylong** [comment]
The most important in Elasticsearch for the timeseries is the mapping. You can see a example here: https://www.elastic.co/blog/elasticsearch-as-a-time-series-data-store

The best is to define your own fields, create indices by day and consume data in using the scroll method.

If you need more explanations, I can help you :)

**Comment by nook24** [comment]
Hi @duylong, if you could help me creating the mapping, would be great.
I struggle with how to save `hostname`, `service_description`and `metric` and fields like this the bast at Elasticsearch...
Even it should be compatible with the Grafana Plugin^^

**Comment by duylong** [comment]
Example mapping:

```
{
        "template" : "statusengine-*",
        "order" : 0,
        "settings" : {
                "index" : {
                        "number_of_shards" : 1,
                        "refresh_interval" : "60s",
                        "codec": "best_compression",
                        "mapper.dynamic": false
                }
        },
        "mappings" : {
                "_default_": {
                        "_all": { "enabled": "false" },
                        "_source" : { "enabled" : "true" }
                },
                "metric" : {
                        "properties": {
                                "@timestamp": {
                                        "type": "date"
                                },
                                "metric": {
                                        "type": "double",
                                        "index": "no"
                                },
                                "hostname": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                },
                                "service_description": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                }
                       }
                }
        }
}
```

Example index name: 
```
statuengine-2017.06 (storage by month) or statuengine-2017.08.19 (storage by day)
```

**Comment by nook24** [comment]
@duylong many thanks, hopefully i will find some spare time to implement this :)

**Comment by duylong** [comment]
I remain available if necessary ;)

**Comment by nook24** [comment]
So, i created a new Branch: https://github.com/statusengine/worker/tree/elastic with the first steps for Elasticsearch, you can test...
For ES5 you need PHP >= 5.6. After you cloned the branch, you need to execute `composer install` or `composer update` to load the new dependencies.

The mapping is defined at: https://github.com/statusengine/worker/tree/elastic/lib/Elasticsearch
Don't miss the new config options: https://github.com/statusengine/worker/blob/elastic/etc/config.yml.example#L154-L161

I was able to save some data to ES:
<img width="738" alt="bildschirmfoto 2017-09-06 um 23 20 08" src="https://user-images.githubusercontent.com/9019992/30135353-b50bc0ca-935a-11e7-9519-a5f4732f37e7.png">
But i have no idea how to query the data - I tried with Grafana but this failed hard :D

**Comment by duylong** [comment]
For the elasticsearch config, the best choice is: 
```
elasticsearch_index: statusengine-metric- => 

elasticsearch_index: [statusengine-metric-]YYYY-MM-dd
elasticsearch_pattern: daily

or

elasticsearch_index: statusengine-metric
elasticsearch_pattern: none
```

No problem, I have PHP7 for testing :)

For using with Grafana, you create a data source. For your example:

```
Http settings:
    url: http://127.0.0.1:9200
    access: direct
Elasticsearch details
    index name: statusengine-metric-
    pattern: no pattern
    time field name: @timestamp
    version: 5.x
```
Save and test :)

For query in Grafana, create a graph panel with this example:
```
Query: hostname:$Host AND service_description:$Service
Metric: "Sum" with value "metric"
```

$Host and $Service are variables defined in templating. For example with $Host:
```
{"find": "terms", "field": "hostname", "size": 1000}
```

**Comment by duylong** [comment]
The "metric" attribute is a value or a string ??? if metric is a string (from your code), you must change the mapping:

```
                                "value": {
                                        "type": "double",
                                        "index": "no"
                                },
                                "metric": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                },
```
In Grafana: "Sum" with value "value"

**Comment by nook24** [comment]
If i use a syntax like
````elasticsearch_index: [statusengine-metric-]YYYY-MM-dd````
in the Statusengine Worker config, does Elasticsearch do the dirty job for me and create the index with the current date, or do i need to create the index by my self?

I sill have the issue, that my Grafana don't want to show any data:
<img width="1435" alt="bildschirmfoto 2017-09-07 um 18 30 03" src="https://user-images.githubusercontent.com/9019992/30178320-c964bc8a-9408-11e7-876e-6c3d4fbf88af.png">
I tried it without creating an template. Could this be the issue?

How ever, i implemented the first basic client for Elasticsearch to the Statusengine Ui, to check if my data looks like expected:
<img width="1350" alt="bildschirmfoto 2017-09-07 um 19 55 40" src="https://user-images.githubusercontent.com/9019992/30178378-fe2751f8-9408-11e7-8392-309fcc1e51f9.png">
Looks not to bad i think :)
Code at: https://github.com/statusengine/interface/tree/elastic

Thinks to do:
- Create index automatically (If required?)
- Create the template if missing automatically
- Delete old data via the Statusengine Cron

Does the interface need to query multiple indices at midnight?

**Comment by duylong** [comment]
Good job !

You must to query multiples indices when you are between multiple periods of time. Use scroll method when you are multiples indices, it's more fast in order to load metrics.

- The index creation is not required
- You should add a option for manage template (load a custom template, template replacement...), for exemple: template (path), template_name (string), template_overwrite (bool)
- Delete old data is easy, just delete the old daily index

Your date field is "@timestamp" or "timestamp" ? code is "timestamp", mapping is "@timestamp". This may be why grafana does not work.

**Comment by nook24** [comment]
Ah, good hint with **@timestamp**. I renamed all timestamps to @timestamp and now also Grafana is working:
<img width="1436" alt="bildschirmfoto 2017-09-08 um 18 42 47" src="https://user-images.githubusercontent.com/9019992/30222039-fdcbe620-94c5-11e7-9e50-244d329b5cdd.png">

Does it make much sense, to give the user the option to change the template? I don't know if there is a use case for, or just an option to break the application...

Looking forward to finish this over the weekend [hopefully :)]

**Comment by duylong** [comment]
Some people will probably want to personalize the number of shards, disable the "_source" to save disk space, change algorithm compression... However you can overload the template, it is not a priority addition, I know you will be asked for a day ;)

You are doing well in the implementation :)

**Comment by nook24** [comment]
I guess the implementation at the SE Worker is almost done.
These are the new config options:
````YML
# Statusengine will create an index template to store performance data to
# Elasticsearch.
# The template is hardcoded and will be managed by Statusengine
# automatically. How ever, you can still change
# important settings.
# If you change any template settings, you need to do this
# BEFORE THE FIRST start of Statusengine Worker,
# or you need to delete/edit the old template manually via Elasticsearch API
elasticsearch_template:
  name: statusengine-metric
  number_of_shards: 2
  number_of_replicas: 0
  refresh_interval: 15s
  codec: best_compression
  enable_all: 0
  enable_source: 1

# Index that will be used to store data in Elasticsearch
elasticsearch_index: statusengine-metric-

# The value of elasticsearch_pattern will be added to the end of your
# defiend elasticsearch_index. It is recommended to terminate
# your elasticsearch_index with an dash, like the example
# index: statusengine-metric-
#
# Available patterns:
# - none     => All data in one index, this will also disable the data clenup for Elasticsearch
# - daily    => statusengine-metric-YYYY.MM.DD
# - weekly   => statusengine-metric-GGGG.WW
# - monthly  => statusengine-metric-YYYY.MM
elasticsearch_pattern: daily

# Set the ip address or hostname for your Elasticsearch system or cluster
# Statusengine will use the HTTP API
elasticsearch_address: 127.0.0.1

# Port where your Elasticsearch server is listening to
elasticsearch_port: 9200
````
Don't miss to update your config, otherwise the default values will be used...

Now Statusengine Worker will do:
- Create the index template if missing
- Insert Nagios/Naemon performance data to given Elasticsearch index
- _Rotate_ index by given pattern
- Delete old indices (as defined by `age_perfdata`)

One quick question about the pattern. I looked at Grafana to get the values , people are used to.
`daily` and `monthly` is clear for me:
````
daily => statusengine-metric-2017.09.10
monthly => statusengine-metric-2017.09
````
But I have no idea about the `weekly` value `GGGG.WW`

What is G and W in a date? Java docs say G is `Era designator` and PHP docs say G is `24-hour format of an hour without leading zeros`. Both will not match to four digits.
As fallback I used the Year and the ISO-8601 week number of year, don't know if this is right or not...
Example: `statusengine-metric-2017.36`

In the next step I will update the Interface, to be able to handle multiple indices.

**Comment by duylong** [comment]
I rarely use this use case, but: 
- GGGG is ISO week year (https://en.wikipedia.org/wiki/ISO_week_date) ;
- WW is the number of week ;

You use "_source" in your code, I don't think enable_source to 0 is possible. _source allows to replay the data to change the mapping for example, that's why I kept it. I advise you to see if you can do without _source in your code.

**Comment by nook24** [comment]
So, a valid name would be `2006-W52` ?

**Comment by duylong** [comment]
Hmmm, I am thinking **2006-52**

**Comment by nook24** [comment]
Hmm, maybe `2006.52`? Because the example is `GGGG.WW` not `GGGG-WW` - confusing me
But `2006.52` is what I use at the moment, so may be all good.

To _source,
First of all, i missed to use the value of the config inside of the mapping template :/
https://github.com/statusengine/worker/blob/elastic/src/Backends/PerfdataBackends/ElasticsearchPerfdata.php#L181-L187

But why should _source => false not be possible?

**Comment by duylong** [comment]
I have followed your example, 2006.52 is the exact value.

You can put _source => false, but you must know that you can not replay the data with Elasticsearch (for example to change the mapping). By experience, we are confronted at one time with the change of the mapping (adding a field, changing the number of shards ...)

**Comment by nook24** [comment]
Perfect, than yes, I would say the ES implementation is done.

I tested _source => false, this is working as well, may be its a bad idea. That's exactly what I meant with
>Does it make much sense, to give the user the option to change the template? I don't know if there is a use case for, or just an option to break the application...

But by default _source is enabled, and _all is disabled. I can enable both by default, if you prefer :) 

And if any one change this, better luck next time
The typical german reaction would be "Tja" :D

What do you think?

**Comment by duylong** [comment]
_source enabled, and _all disabled are a good compromise. If person wants to disable _source, he can do it on all of these indexes. The opposite is not possible easily.

**Comment by nook24** [comment]
Ok, now everything is broken, i guess its because of the bulk inserts but I don't know...

I will continue tomorrow eventing.

**Comment by nook24** [comment]
Ok, all done.
Bulk Index is fixed, and also the Interface is now ES ready.
Happy testing :)

**Comment by duylong** [comment]
You should control the fields name, Elasticsearch can't accept dot in the fields name ;)

**Comment by nook24** [comment]
I don't have any dots in my names, or do you mean the index name

**Comment by duylong** [comment]
Ah yes, I thought about the content but that's allowed. Sorry.

Just a question, your compression algorith use internal method or backend method? Elasticsearch can return directly AVG, MIN and MAX value.

**Comment by nook24** [comment]
I use an internal method, because of two reasons:

1.  Easy implementation across multiple backends
2. Compression to 500 data points, to avoid browser crashes

**Comment by nook24** [comment]
If you finished your tests, you can close this issue down. If you don't find any bugs, i will merge it into the master branch, build a new version and write the documentation :)

**Comment by duylong** [comment]
I test with Elasticsearch 5.5.2. We should modify the template because somes options are deprecated:

```
[2017-09-14T23:43:08,182][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [hostname]
[2017-09-14T23:43:08,182][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [service_description]
[2017-09-14T23:43:08,183][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [metric]
[2017-09-14T23:43:08,184][WARN ][o.e.d.i.m.TypeParsers    ] Expected a boolean [true/false] for property [index] but got [no]
```

TODO: 

```
string => keyword
no => false
```

**Comment by nook24** [comment]
I updated the index and use now `keyword`. If I understand the docs correctly this should be the best choice.
I also removed `not_analyzed ` completely. No warnings on (my) 5.5.2 anymore

**Comment by duylong** [comment]
Strange, the template is created but no indice in Elasticsearch... No errors in the backend, my config seems correct, number_perfdata_worker to "1", perfdata_backend to "- elasticsearch". I forgot a few things?

**Comment by nook24** [comment]
I moved the template into a new class, may be the php autoloader can't find the class.
Had you run `composer update` or `composer dump-autoload`?

**Comment by duylong** [comment]
I use composer update, but the problem does not come from this change, it was before.

My index is always missing from the last elastic branch. 

My StatusengineWorker.php output:

```
# /usr/bin/php /opt/statusengine/worker/bin/StatusengineWorker.php
statusengine-worker[17]: Starting Statusengine-Worker Version 3.1.0
statusengine-worker[17]: Fork new host status worker
statusengine-worker[17]: Fork new service status worker
statusengine-worker[17]: Fork new log entry worker
statusengine-worker[17]: Fork new state change worker
statusengine-worker[17]: Fork new host check worker
statusengine-worker[17]: Fork new service check worker
statusengine-worker[17]: Fork new misc worker
statusengine-worker[17]: Fork new performance data worker
statusengine-worker[17]: Finished daemonizing
statusengine-worker[17]: Catch monitoring restart. Trigger callbacks...
statusengine-worker[72]: Elasticsearch index template missing - I will create it
```

**Comment by nook24** [comment]
Hm, the only thing i changed is the template stuff...
Did you delete the template and all indices?
If I stop Statusengine Worker, delete the template, drop all indices and start the worker again, everything is looking good to me

Template:
![bildschirmfoto 2017-09-15 um 19 21 23](https://user-images.githubusercontent.com/9019992/30495143-1a16ec50-9a4b-11e7-8170-497ad5426aa6.png)

Index:
![bildschirmfoto 2017-09-15 um 19 23 08](https://user-images.githubusercontent.com/9019992/30495163-2b1ed850-9a4b-11e7-870b-d6494f08e8e3.png)

Statusengine Interface:
![bildschirmfoto 2017-09-15 um 19 23 41](https://user-images.githubusercontent.com/9019992/30495181-3bcf5706-9a4b-11e7-9f0b-6b0fbf1a5487.png)


Not much data, due to i dropped all^^

**Comment by duylong** [comment]
No indices, no templates, clean installation.

Worker PHP version:
```
php --version
PHP 7.1.9 (cli) (built: Aug 30 2017 20:06:08) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

No problem with Statusengine Interface, I have only "404 not found" because indice not exist: 

```HEAD /statusengine-metric-2017.09.15 HTTP/1.1
host: elasticsearch:9200
Content-type: application/json
Accept: application/json

HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 443
```

For Statusengine Worker, I don't see bulk queries, just the template creation:

```
HEAD /_template/statusengine-metric HTTP/1.1
host: elasticsearch:9200
Content-type: application/json
Accept: application/json

HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 508

Nothing else.
```

Hmmm, when I see historical data, the performance data records is 0:

```
Processed Historical data:
===================================
Total processed host check records: 106
Total processed host check records last minute: 2
Total processed service check records: 108
Total processed service check records last minute: 2
Total processed log entry records: 35
Total processed log entry records last minute: 0
Total processed state change records: 3
Total processed state change records last minute: 0
Total processed performance data records: 0
Total processed performance data records last minute: 0
```

Yet I have metrics in my checks, for example check_mem:
```
    TOTAL=16327680KB;;;; USED=16020588KB;;;; FREE=307092KB;;;; CACHES=11854564KB;;;;
```

I don't understand^^

**Comment by nook24** [comment]
Do you use a proxy server? If yes make sure that `disable_http_proxy` is set to `1` in the Worker config, or remove all proxy settings from the system for testing.

In addition, run the command `gearadmin --status` and check if there is a worker connected to the `statusngin_service_perfdata` queue:
````
                   Waiting Jobs / Running Jobs / Available Workers
[20:45]root@statusengine:~# gearadmin --status
statusngin_service_perfdata    0    0    2
````
If there is no Worker connected to the queue, I guess it crashes.

If there is a Worker connected, and you don't use a proxy, stop Statusengine Worker, and check the output of `gearadmin --status`, if Nagios/Naemon writes data into this queue or not.

Have you modified your broker options? `use_service_perfdata=1`

**Comment by duylong** [comment]
It seems after 23pm (time to be confirmed, after midnight it is certain), I don't see new events in the graphs. Did you see this issue ?

**Comment by nook24** [comment]
I guess you mean, that the Statusengine Ui will not show the new data? If so, I fixed this yesterday with https://github.com/statusengine/interface/commit/41fe5427ad3afdb58a606004866d15af53db3823

Can you please update your Interface and recheck?

**Comment by duylong** [comment]
I tested last night and I still have the same worries, no display of graphs after midnight.No problem the next day after a good sleep O :)

Else, I prefer elasticsearch_index to "statusengine-metric". We can automatic add "-" if elasticsearch_pattern is not none.

**Comment by nook24** [comment]
You can also remove "-" manually if pattern is set to `none` :P

I tried to reproduce the midnight issue, but it was working on my system. I used 20.09.2017 - 21.09.2017 as test date.

First of all, SE Worker create the new index, and only save data to the new index:
<img width="762" alt="bildschirmfoto 2017-09-21 um 00 07 37" src="https://user-images.githubusercontent.com/9019992/30823777-9d6230f8-a22d-11e7-89fa-00cbb6c4af42.png">

SE Ui show the Graph form 20.09 to 21.09 00:05 (No page reload, only auto update)
<img width="1439" alt="bildschirmfoto 2017-09-21 um 00 07 14" src="https://user-images.githubusercontent.com/9019992/30823788-ac2db742-a22d-11e7-92ef-d668ad844125.png">

Also the month view works: (also no page reload)
<img width="1437" alt="bildschirmfoto 2017-09-21 um 00 09 42" src="https://user-images.githubusercontent.com/9019992/30823828-d3f9fa92-a22d-11e7-9e6c-560b3a91d277.png">

Also a page reload works...


I noticed that Grafana has some issues:
<img width="1437" alt="bildschirmfoto 2017-09-21 um 00 07 29" src="https://user-images.githubusercontent.com/9019992/30823889-074ba63e-a22e-11e7-866a-c75961253422.png">
Grafana don't display any data, but I don't know why?!

**Comment by nook24** [comment]
Whops, wrong button

**Comment by nook24** [comment]
But Grafana is able to display all records, if I tick the complete month, strange...
<img width="1440" alt="bildschirmfoto 2017-09-25 um 20 22 38" src="https://user-images.githubusercontent.com/9019992/30824283-5858c088-a22f-11e7-8830-bba713ee3a03.png">

Maybe you have any ideas?

**Comment by duylong** [comment]
Yes I can also remove "-" but the default index is ugly if I use pattern^^

Strange, for me, it does not appear after midnight, the metric data continues to be fed (graph timespan: 2.5h)

For your problem, I wonder if there is not a problem with timezone. By default, Grafana use the local browser time, what is the timezone of the @timestamp field when you insert the metrics?

**Comment by nook24** [comment]
So Statusengine UI uses local browser time, and Grafana should do this as well. All systems using Europe/Berlin as timezone.
How every, the unix timestamp is free of timezone issues ^^

**Comment by nook24** [comment]
I tested this again and still can't confirm the issue. 
Only Grafana has an issue at midnight.

I will merge this into the next version, add the documentation and close this issue down...

**Comment by duylong** [comment]
It's stable on my side except for the display problem at midnight for me :) If I find the problem, I would open another issue.

**Comment by nook24** [comment]
Merged into 3.2.0 :)
Docs are available at https://statusengine.org/tutorials/Elasticsearch-Perfdata-Backend/
